### ISSUE TITLE
open-simplex-noise* are all HTML rather than source

### ISSUE THREAD

**Issue by gflofst** [LLNL/MACSio#1]
The files were not inserted correctly. Also, there should be some good reference back to the original for attribution.

**Comment by markcmiller86** [comment]
Oops. Thats ugly. Ok, went and copied the 'raw' sources into this dir. These are here as a fallback in case I need to remove Perlin routine in macsio_data.c

**Comment by markcmiller86** [comment]
I relied upon copyright notice at top of source code to serve as reference. A google search on source file name takes you right to github source file.
