### ISSUE TITLE
segfault with intel compiler

### ISSUE THREAD

**Issue by jdomke** [LLNL/MACSio#11]
https://github.com/LLNL/MACSio/blob/e8bece99bfa5eab9355549bb587ee36aec9d6c67/macsio/macsio_clargs.c#L234

The way this code is written triggers an segfault (null pointer dereference later in the loop) with intel compiler due to undefined behavior of the language. gnu does not reinitialize recurring variable declaration, however intel does, so the linked line will reset both pointers to NULL in every iteration!

Best,
Jens

**Comment by markcmiller86** [comment]
Thanks for pointing this out. Oversight. Those vars should have been declared outside the loop. And, it looks like in my git naievety, I wound up fixing on master.
