### ISSUE TITLE
H5pubconf.h not in my configuration

### ISSUE THREAD

**Issue by gflofst** [LLNL/MACSio#3]
I have a H5pubconf-64.h. I think there is a difference in how it gets configured for 64-bit setups or something? There are some problems with my setup. Please close this issue. Will make a new one if it is still a problem.

**Comment by markcmiller86** [comment]
Hmm. Wonder if HDF5 names that file differently depending on config options. If so, MACSio needs to be smart enough to include the correct one, either with a -DUSING_64BIT_HDF5 or something else.

**Comment by gflofst** [comment]
The module on chama at Sandia is setup that way. When I pointed things "correctly", it broke elsewhere in HDF5 headers looking for the version without -64 suffix. I switched to my private HDF5 build and it worked fine.

**Comment by markcmiller86** [comment]
Ok, on that basis, lets close this.
